motor_num: 31        # 电机数量
zero_motion_onnx_path: "../sitrise/model/STNAD2_0528.onnx"  # 可填绝对路径，或相对 layupzero/ 的路径
zero_motion_frame: 0  # 从 motion 的第几帧读取 joint_pos 作为 zero_positions

zero_positions: [
    -0.25, 0, 0, 0.5, -0.25, 0.0,   # 左腿
    -0.25, 0, 0, 0.5, -0.25, 0.0,   # 右腿
    0.0, 0.0, 0.0,                   # 腰
    0.0, 0.3, 0.0, -0.3, 0.0, -0.0, 0.0, # 左臂
    0.0, -0.3, 0.0, -0.3, 0.0, -0.0, 0.0, # 右臂
    0.0, 0.0,                   # 头部0号和1号
    ]  
    

kp_pos: [
        880, 880, 640, 1240, 53, 53,
        880, 880, 640, 1240, 53, 53,
        410, 410, 410,
        100.0, 100.0, 90.0, 90.0, 20.0, 20.0, 20.0,
        100.0, 100.0, 90.0, 90.0, 20.0, 20.0, 20.0,
        20.0, 20.0,
]
kd_pos: [
        33, 33, 25, 48, 2.1, 2.1,
        33, 33, 25, 48, 2.1, 2.1,
        41, 41, 41,
        7.4, 7.4, 5.9, 5.9, 1.40, 1.40, 1.40,
        7.4, 7.4, 5.9, 5.9, 1.40, 1.40, 1.40,
        1.0, 1.0,
]

interp_step: 0.001 #  控制插值速度
interp_max: 0.9
num_obs : 125
close_threshold: 20.0 # 关节位置差值阈值，单位：度